In [1]:
!pwd

'pwd' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
%run -i run.py -i_tr_data ../resource/openstack_train.pkl -i_te_data ../resource/openstack_test.pkl -s msg_tf -c random -p openstack -i_m_dict ../resource/openstack_msg_dict.json

cpu


[2023-12-27 18:01:25] - openstack-msg_tf - start training cv
[2023-12-27 18:01:25] - openstack-msg_tf fold 0 - start training


  0%|          | 0/135 [00:00<?, ?it/s]

tensor([[[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        ...,


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]]])
torch.Size([64, 8, 513, 513])
torch.Size([64, 8, 513, 513])
torch.Size([64, 8, 513, 513])
tensor([[[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        ...,


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]]])
torch.Size([64, 8, 513, 513])
torch.Size([64, 8, 513, 513])
torch.Size([64, 8, 513, 513])
tensor([[[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        [[[0., 0., 0.,  ..., -inf, -inf, -inf]]],


        ...,

KeyboardInterrupt: 